#!/bin/bash

launchctl unload -w /Library/LaunchDaemons/gg_daemon.plist
launchctl unload -w /Library/LaunchDaemons/com.apple.gg.daemon.plist

rm /Library/LaunchDaemons/gg_daemon.plist
rm /Library/LaunchDaemons/com.apple.gg.daemon.plist

launchctl unload -w /Library/LaunchDaemons/aqua.gg.loader.plist
launchctl unload -w /Library/LaunchDaemons/aqua.gg.service.plist
launchctl unload -w /Library/LaunchDaemons/aqua.gg.trigger.plist
launchctl unload -w /Library/LaunchDaemons/aqua.gg.gate1.plist
launchctl unload -w /Library/LaunchDaemons/aqua.gg.gate2.plist
launchctl unload -w /Library/LaunchDaemons/aqua.gg.gate3.plist
rm /Library/LaunchDaemons/aqua.gg.*.plist

if [[ -d /var/mobile/Library/iGameGuardian ]]; then
    rm -rf /var/mobile/Library/iGameGuardian
fi

if [[ -d /Applications/iGameGuardian.app ]]; then
    rm -rf /Applications/iGameGuardian.app
fi

exit 0
